In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Evan"],
    "Age": [19, 22, 21, 20, 23],
    "Score": [78, 85, 92, 88, 90]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   19     78
1      Bob   22     85
2  Charlie   21     92
3    Diana   20     88
4     Evan   23     90

In [3]:
df.head(3)

      Name  Age  Score
0    Alice   19     78
1      Bob   22     85
2  Charlie   21     92

In [4]:
df.describe()

             Age      Score
count   5.000000   5.000000
mean   21.000000  86.600000
std     1.581139   5.458938
min    19.000000  78.000000
25%    20.000000  85.000000
50%    21.000000  88.000000
75%    22.000000  90.000000
max    23.000000  92.000000

In [5]:
df["Score"].mean()

np.float64(86.6)

In [6]:
df[df["Age"] > 20]

      Name  Age  Score
1      Bob   22     85
2  Charlie   21     92
4     Evan   23     90

In [7]:
df[df["Score"] > 80]

      Name  Age  Score
1      Bob   22     85
2  Charlie   21     92
3    Diana   20     88
4     Evan   23     90